spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/solvatest
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto:  validate
    show-sql: false
    generate-ddl: false

exchange:
  key: ${URL+KEY}


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher